### ISSUE TITLE
Model meshes are sharing material

### ISSUE THREAD

**Issue by asalga** [gladiusjs/gladius-core#109]
When creating an instance of a Model component, a mesh and material must be provided.

``` JavaScript
new engine.graphics.component.Model({
  mesh: resources.mesh,
  material: resources.material
})
```

When many Models are created with the same procedural mesh but with different materials, the meshes end up sharing a single material. The problem seems to be related to model.mesh._cvr.mesh.materials. When creating a new material, it is appended to the 'shared' materials array.

The current workaround is to create a unique procedural mesh and material for each Model.

**Comment by modeswitch** [comment]
Fixed in gladius-cubicvr. Should work properly now in wip-core.
