### ISSUE TITLE
Textures with transparency are white if a light is not added to scene

### ISSUE THREAD

**Issue by asalga** [gladiusjs/gladius-core#111]
If a light isn't in a scene, the transparent parts of textures become white.

http://scotland.proximity.on.ca/asalga/gladius/gladius_transparency_issue.png

The workaround is to create a dummy light

``` JavaScript
new engine.graphics.component.Light({
  type: "point",
  method: "dynamic",
  diffuse: [0, 0, 0 ],
  specular: [0, 0, 0 ],
  intensity: 100,
  distance: 0
 })
```

**Comment by modeswitch** [comment]
This is an issue with the CubicVR extension.

**Comment by modeswitch** [comment]
https://github.com/gladiusjs/gladius-cubicvr/issues/6
