### ISSUE TITLE
Messenger should report keydown only once, optionally report each frame

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#12]
Send keydown events only once for the first time. Clients can optionally specify that they wish to receive the event each frame.

**Comment by secretrobotron** [comment]
We spoke about having a "browser" or "legacy" mode for this feature too, where the event is received exactly as one would think from the browser.
e.g.
1. keydown event
2. wait a bunch of time as specified by the OS
3. keydown event
4. keydown event
5. keydown event
6. ad nauseum

In other words, it's a straight pass-through of keyboard events from the browser.

I don't know if this is terribly necessary, but it might be a good idea for people who are implementing things like complicated menu UI systems with Paladin.

**Comment by modeswitch** [comment]
I don't think there's a reason to support the current behaviour. Either you want to get the event every frame, or you want to get it once and store it internally.
