### ISSUE TITLE
The real time clock the engine offers is not as accurate as the new high performance timer

### ISSUE THREAD

**Issue by dmose** [gladiusjs/gladius-core#203]
There's probably an actual user story here, but I don't have enough of a feel for all the motivations here nor the degree of difference and how that relates to common uses, so I'm not sure how to frame it.

**Comment by modeswitch** [comment]
Can you be more specific? The engine provides two system clocks that are updated from Date.now. I plan on pushing this logic into the Loop object though and making it easier to choose an implementation so we can support HPT where they exist.

**Comment by dmose** [comment]
I was confused about Date.now, I've updated to be more accurate.

**Comment by modeswitch** [comment]
Can I convert this into a user story? I'm not sure there's much to discuss here.

**Comment by modeswitch** [comment]
I've created a user story for this issue: https://github.com/gladiusjs/gladius-core/issues/215
