### ISSUE TITLE
Configuration registry

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#21]
We need a configuration registry to store config parameters for Gladius and its services.
- The configurator instance needs to be created very early, so we can use it to configure the engine and other subsystems. For example, we can use it to enable or disable certain other services. The configurator should be partially constructed, like other modules.
- The configurator should accept a default configuration that is defined somewhere internally that contains sane defaults for most configuration parameters.

Example: create a new Configurator instance

``` javascript
var configurator = new Configurator( defaultConfiguration );
```
- Configurations should be specified in JSON.
- Configurations should be organized into a tree structure, with top-level nodes being core, graphics, sounds, etc. Using a path separator like '/' seems sane.
- The configurator should be able to load configurations from a URL (including file://?) to customize the engine and its services by modifying the default settings.

Example: loading a configuration

``` javascript
engine.configurator.load( URL );
```
- The configurator should provide get(), getPath() and set() methods to retrieve part of the configuration tree, or to set a value in the tree.

Example: setting a configuration value

``` javascript
engine.configurator.set( '/graphics/render/mode' ) = 'wireframe';
```
- The getTree( path ) method should return a configurator object for the subtree defined by path.

Example: getting a configuration path

``` javascript
var graphicsConfig = engine.configurator.getPath( '/graphics' );
graphicsConfig.set( '/render/mode' ) = 'wireframe';
```
- Other code should be able to register interest in a configuration subtree and provide a callback that can be invoked, with the name of the updated entry, when changes occur in that subtree. Should also be able to call ignore() on the return value of getPath() to unregister the callback from the change event.

Example: defining a callback to run when things change

``` javascript
var graphicsConfig = engine.configurator.getPath( '/graphics', function( path ) {
    // do something with path
});

...

graphicsConfig.ignore();
```
- The configurator should be able to serialize the configuration tree back into local browser cache, so that changes made while the engine is running can persist.

Example: storing the configuration to a browser cache

``` javascript
engine.configurator.store( URL );
```

@northWind87 will work on this.

Stories and tasks for this issue are [here](https://www.pivotaltracker.com/projects/373719).

**Comment by NorthWindH** [comment]
Alright some questions/clarifications, I apologize in advance if these points are noobie :) :

To clarify the pathing, would the following describe some arbitrary values embedded within some categories/subcategories?

``` javascript
var myJSONObject = {
    "cat1/subCat1/subCat2" : "value",
    "cat1/subCat1" : "otherValue"
};
```

The watch mechanism:
Is it the only way to query the registry? Would it make sense to also have something like a `get` command?

``` javascript
var bMySetting = engine.configurator.get("cat1/subCat1/subCat2");
```

I see a load command in the registry, would it also make sense to have a `set` command for setting a single value? I guess the question is, do we want programmatic set-ability ie:

``` javascript
engine.configurator.set("cat1/subCat1/subCat2") = "someValue";
```

Also, shouldn't the watch command accept a second argument which is the callback function provided by the external code? If I've missed something obvious here then I apologize in advance, I've been up for an unnatural amount of time :)

``` javascript
engine.configurator.watch( treePath, callback );
```

Here's how I see the behaviour of the registry:

The registry is essentially a passive storage medium. External code sets keys to values within the registry; external code also queries the registry for certain keys, their values are returned. The registry does **_not**_ act based upon values being entered or changed within the registry, aside from calling callback functions where required. Would this be a more or less accurate definition of the behaviour of the registry?

**Comment by humphd** [comment]
A couple of thoughts:
- I think watch() should be listen()
- I think we should consider how offline will work here, and how persistence will bubble from local to remote, when saving state.
- Similar to above, how to do we want to store these options locally (indexdb, storage, ???) in addition to pushing remotely.

Mozilla has a similar problem it solves with nsIPrefBranch, see https://developer.mozilla.org/en/Code_snippets/Preferences for a discussion of our preferences.  One thing you can do with Mozilla's preference system is tear-off a particular branch, say graphics, and not have to deeply index every property lookup (e.g., 'cat1/subCat1' can get saved for later queries).

How can users override settings?  Can we pass them on the query string or as part of the hash, for example?  It would be nice, for testing and such, to be able to pass a config option via url without a server or file load.

**Comment by humphd** [comment]
Another thought: do we expose property paths directly on the object?  For example:

engine.configurator.get('some/long/path/and/value')

vs.

engine.configurator.some.long.path.and.value;

If we are careful to wrap these with getters/setters vs. raw references or values, the latter might be really nice.

**Comment by humphd** [comment]
Do we also want to overload this for localization?  That is, do we want this to be where strings live for different locales?

**Comment by dmose** [comment]
I'd love to see what sorts of preferences you think would be the most common use cases here.  Or is that something we only figure out with experience?

**Comment by humphd** [comment]
I'm realizing, as I think more on this, that I'm conflating engine configuration with game configuration.  We should probably split those in a useful way, and that probably wants another bug, if not already filed.

Dan, I can imagine wanting to force certain things, perhaps in the graphics engine you can force "mobile" style properties, or the number of web workers to spawn, or the default number of audio nodes to clone for sound effects, etc.

**Comment by dmose** [comment]
My question was in large part an attempt to encourage us to consider what we really truly need, and to encourage us to implement a bit lazily so that we don't end up with over-engineered or even unnecessary code.  What I'm wondering is, should we wait and the let the design be shaped by actual specific requirements from games or engine-functionality in-progress.

So far, I haven't heard specific, current needs articulated, but I suspect they do exist!

**Comment by NorthWindH** [comment]
I agree humph, I think that user-accessible preferences should be split from the internal engine configuration registry; perhaps another bug should be opened for user preferences while this bug continues to focus on internal configuration registry requirements?

I also think that something like localization has more to do with the visual interface than it does with a setting itself; ie the key for a "cat1/subCat1/myUnicodeSetting" setting can be stored in unicode and registered against a display mechanism which can then display that setting (if it should be displayed) to the user in any number of different languages/localizations based on the user's language settings.

**Comment by modeswitch** [comment]
OK, here goes:

@northWind87
1. Yep, your JSON looks correct.
2. Yes, get() and set() make sense.
3. As humph mentioned, watch() should be listen(). There should also be an ignore() to stop listening.
4. Your summary is correct, except that the registry gets an initial configuration passed into it by the engine.

@humphd
1. Yes, watch() should be listen() to keep the API sane.
2. I'm not sure your comment about offline behaviour makes sense. The default configuration is packaged with the engine. Additional configuration is done by game code, and that (along with the default config) gets packed up with the final game. Any other changes beyond that are made by the user, and only need to be stored locally. The only reason we might want to store things remotely is if we want to build a cloud service for maintaining user configs across machines.
3. Local storage for configs is something I'm not sure about. We have a number of options here. Anything that will hold a JSON file will do.
4. Users can change some settings, if they are exposed in the UI by the game developer. Things like sound and music volumes, FOV, and key bindings should be customizable.
5. I don't think the engine needs to worry about reading configs from the URL. If the game wants to do this, it can parse them and send them along when it creates an engine instance. So I don't think we need to handle this explicitly.
6. My only concern about using getters/setters for configs is that it could be confusing if there are other methods on the configurator.
7. I don't think we want to store localized content here. That should be a loadable asset instead. However, game code could store it's localization settings in the registry (EN_US, for example).
8. Yes, the registry is intended to store configuration for the engine and its subsystems (like which subsystems to initialize, and settings for those subsystems), and also for the game to store its configuration.

@dmose
We definitely need a way to configure the engine. Most game engines have a long list of configurable options (gravity, render mode, sound volume, languages, mouse sensitivity, autosave options, etc...) and I don't think gladius will be an exception.

**Comment by modeswitch** [comment]
@northWind87
I don't think there needs to be a separate place to store user preferences; User is in this case the player, not the game developer. The player has access to change whatever settings are exposed by the game developer. As an example, we might have

"/core/threads" : 2
"/graphics/rendermode" : 'wireframe'
"/sound/volume" : 89

for the engine and, say our game is rescuefox,

"/rescuefox/language" : 'EN_US'
"/rescuefox/autosave" : 60

**Comment by NorthWindH** [comment]
Ok I'm going to try and get an early version of this going unless there are any objections, can someone assign this one to me?

**Comment by NorthWindH** [comment]
Writing tests for the requirements, put up a number already https://github.com/northWind87/gladius/blob/develop_issue_21/test/core/Configurator.js

for now set is using configurator.set(key, value); syntax, couldn't find how to facilitate configurator.set( key ) = value; syntax, any ideas?

**Comment by modeswitch** [comment]
configurator.set( key, value ) seems reasonable to me.

**Comment by NorthWindH** [comment]
Ok perfect, moving forward with that in mind. I've put up some design ideas on my forked wiki, comments?
https://github.com/northWind87/gladius/wiki/Issue-21---Configurator-Registry-Design

**Comment by NorthWindH** [comment]
Feature suggestion: configurator.set() should be able to accept and apply a json object eg:

```
var myJSON = {
    '/foo' : 'value',
    '/foo/bar' : 'otherValue'
};

engine.configurator.set( myJSON );

equal( engine.configurator.get( '/foo' ), 'value' );
equal( engine.configurator.get( '/foo/bar' ), 'otherValue' );
```

**Comment by modeswitch** [comment]
Rather than having set() do this, please add an update() method instead. So load(), with either a URL or a piece of JSON will set the configuration, removing existing nodes. Update() will change it without removing existing nodes.

Thoughts?

**Comment by NorthWindH** [comment]
That seems to make sense. I would also suggest throwing an optional second parameter on load which accepts a boolean such that it forces load to perform an additive change instead of the default destructive change.

**Comment by NorthWindH** [comment]
The configurator doesn't seem to be dependent on the existence of a Gladius instance in any way, is there a value in designing it to be partially constructed?

**Comment by modeswitch** [comment]
No. Component is the same way, if you want to have a look.

**Comment by NorthWindH** [comment]
Initial implementation of configuration registry ( aside from load/store ) is ready for peer review. I tried to follow style guidelines exhibited in other files as much as possible.

files of note:
`src/gladius-src.js`
`src/core/Configurator.js`
`test/core/Configurator.js`

Repo/branch: https://github.com/northWind87/gladius/tree/develop_issue_21
Commit: [9b5c7d5ca2583508e02cd49286b9bb684b49b85a](https://github.com/northWind87/gladius/commit/9b5c7d5ca2583508e02cd49286b9bb684b49b85a)

Please note the huge hack in src/core/Configurator.js:148 and the associated hack in test/core/Configurator.js:118, ideas on a better way to test construction/defaultConfig loading?

**Comment by NorthWindH** [comment]
Pull request: https://github.com/alankligman/gladius/pull/52

**Comment by NorthWindH** [comment]
A couple of questions that I threw at @alankligman over irc but looking for other input as well:
1. With regard to configurator.store and configurator.load, our original spec says that load should load from a URL ( so xhr ) while store will save to local storage ( so window.localStorage )
   - How should data stored to a browser's storage be restored?
   - Should it simply be loaded automatically?
   - Perhaps another function all-together should be added?
2. Should store be able to store back to a remote web service should a URL be provided? This is touched upon in the spec but is not very clear

edit: also, [pull request 52 updated October 27](https://github.com/alankligman/gladius/pull/52#issuecomment-2539095), looking for review

edit2: pull request further updated, implemented:
load, store, clear, getJSON

Calling this "release" 0.2 :)

**Comment by NorthWindH** [comment]
I aimed to keep the load/store interface very close with what was earlier discussed. At the moment, here is where it stands:

### Load:

``` javascript
// load( [ clearBeforeLoad ][ , URL [ , callback ] ] )
function load( clearBeforeLoad, URL, callback );
```

Loads registry either from a url or from local storage ( cookie ). At the moment, only loading from a cookie has been implemented; more on this in a bit.

#### Behvaiour:
- Loads data into the configurator instance.
- Affects the configurator instance node and all child nodes to it.
- Does not affect parent configuration nodes.

#### Parameter Details:
- Accepts three optional parameters.
- If clearBeforeLoad is set to true, this configurator's configuration options are cleared before new ones are loaded. If false, contents are not cleared prior and any colliding configuration options are overwritten; this is the default.
- If no URL is provided then configuration is loaded from local storage. This is a blocking/synchronous operation.
- If a URL is provided then an asynchronous XHR request is made to the given URL. The function expects a JSON object result.
  - If a callback is provided, it will be called when the JSON object has been retrieved and the configurator has been updated.
    - The callback should accept the configurator instance as its only parameter.
    - The callback will not be called if no URL is provided.

### Store:

``` javascript
// store()
function store();
```

Stores configuration options to local storage.

#### Behaviour:
- Stores data from this configurator instance node and all child nodes.
- All store paths are pre-pended with the configuration path of parent nodes leading to this configurator instance node.
- Stores merge data, ie storing from a child node configurator instance should not affect data already stored from parent configurator instances.

#### Limitations:
- At the moment, no other means of storing are supported. Is anything more desired from this function? Perhaps saving to the web? Not sure how we would go about this.
- The cookie's name, lifetime and path are currently fixed in stone ( "gladius_registry" ). The implication is that all gladius instances share the same local storage, for better or for worse. 
- Concurrent and frequent stores/loads **will** lead to race conditions and possibly unpredictable loads/stores. A load/store event listener system may be desired.

---

I've also added two light-weight simple function functions:

### Clear:

``` javascript
// clear()
function clear();
```

Clears the configurator instance of all configuration options.
- Affects all child configuration nodes.
- Does not affect parent configuration nodes.

### getJSON:

``` javascript
// getJSON()
function getJSON()
```

Creates a JSON representation of this configuration instance and returns it.
- The JSON captures the data of this configuration instance node and all child nodes.

**Comment by NorthWindH** [comment]
New release, keeping thread up-to-date: [pull request thread](https://github.com/alankligman/gladius/pull/52#issuecomment-2845944)
