### ISSUE TITLE
V8/Spidermonkey support for Gladius

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#26]
Not sure exactly what this involves. At very least we need a WebGL context.

**Comment by GUSCRAWFORD** [comment]
I'm pretty experienced in JavaScript and I've been developing a Client-Side web-app framework.
I'm going to stab at this.  Does this sound right?  A JS API that allows wrapping a <canvas> and supporting gladius operations through it?  Am i even vaguely close or on the right track to solving this issue with my description?

**Comment by modeswitch** [comment]
I'm not sure I understand what you mean. Could you elaborate?

Gladius requries a WebGL context in order to run its graphics service. I think this project is already doing this, or at least something similar: https://github.com/tmpvar/WebGL-standalone.

**Comment by GUSCRAWFORD** [comment]
Hmmmmm.... I've looked pretty hard at WebGL standalone now.

I think I need to take a close look at gladius before I say too much more...

that said...

For the end-programmer, there is an object he/she can create call it Context.
so maybe somewhere in html, <context id="ctxViewport"></context>.

and in javascript, sometihng like var myViewport = new Context("ctxViewport");

and then of course Context's scope holds its own properties and calss initWebGL(); or its variant for v8.

This to me sounds like it meets the minimum requirements for your milestone.  Lemme know whatcha think!

**Comment by GUSCRAWFORD** [comment]
Hi Alan,

I setup a repo and commited my first stab at this web gl context in repo.

You can check out the source file I added https://github.com/GUSCRAWFORD/gladius/blob/develop/src/webgl.js

I've been tracing through gladius and and the paladin-demo to try and get a perspective on this, and of course I've been ripping the MDN's WebGL reference.  Hope some of this is helpful.
