### ISSUE TITLE
Tasker rework

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#3]
Currently we handle all tasks for a particular frame before returning control to the browser. What is the impact of yielding after each task instead?

There's also an issue with using setTimeout() to control context changes.

**Comment by modeswitch** [comment]
There is definitely a performance problem here for large numbers of tasks. We need a way to yield back to the browser, but also need to control when redraw happens so that all tasks can be executed for each frame.

**Comment by modeswitch** [comment]
This is worth checking out. An alternate way of handling tasks:

http://dbaron.org/log/20100309-faster-timeouts

**Comment by secretrobotron** [comment]
This is actually really interesting. The messenger or some governing body should probably get involved so we can multiplex the "onmessage" handler for workers, etc.

**Comment by modeswitch** [comment]
I've reworked the tasker into the scheduler, which now covers this functionality.
