### ISSUE TITLE
Math module

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#43]
I've started implementing a math module. Right now it's written into the global environment because it doesn't rely on an engine instance. Implementations are required for Vector (2, 3, and 4), Matrix (2, 3, and 4) and Quaternion.

Existing code is in src/common/Math.js, and unit tests are in the test/ subtree.

This chunk of code needs to be split out into a separate repository for both Gladius and CubicVR to use.

**Comment by humphd** [comment]
Topheru is interested in this, but we need more info.  Can we get this bug fleshed out with more details please?

**Comment by modeswitch** [comment]
The bulk of the work here is to provide implementations for many of the functions and unit tests. I also want to get some performance numbers, but that doesn't have to be part of this issue.

I will break this up into user stories in pivotal.

**Comment by JekyJaw** [comment]
I found some neat peace of code in JS for Vectors and Matrix. Someone might be interested in it. Here is the link: 

http://sylvester.jcoglan.com/#download

There is also a manual written for each of the functions available online.Hope it helps!

**Comment by modeswitch** [comment]
Module implemented in gladius.math.
