### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#44]
I have some concerns about adopting [this](http://nvie.com/posts/a-successful-git-branching-model/) branching model for Gladius. Consider this scenario:
- We have made several releases, 1.0, 2.0 and 3.0.
- Each major version has significant changes, such that it would be non-trivial to port a game between versions.
- Games have been deployed based on 1.0 and 2.0, and we discover a bug that affects all releases.

Using the workflow above, it is not possible to fix the bug in all the releases. Only in 3.x could we fix it. I don't see a way to fix the critical bug that doesn't require users to port their code to the 3.x that contains the fix.

Instead, we may need to maintain several production branches, instead of using master as the only production branch. I don't think git requires that we have a master branch at all, so do we even want one?

Thoughts?

**Comment by dmose** [comment]
If we had to, we could cut production branches based at tags from master.

**Comment by modeswitch** [comment]
I'm not even sure we need a master branch. Since we will likely need to support multiple production branches, I we can just make release branches from develop and tag them as we need. So instead of having the blue branch (in the diagram), we would have a bunch of green branches, with red (hotfix) branches jumping off and back onto the green ones instead.

I need to think a bit more about what this means in terms of porting bug fixes between release branches.

**Comment by dmose** [comment]
I've heard people say good things about flows similar to this one as well lately; I haven't yet read it closely enough to have an opinion myself.  http://scottchacon.com/2011/08/31/github-flow.html
