### ISSUE TITLE
Agile issue-tracking tool

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#46]
We are going to need a better tool than Github's Issues to log and track work for this project. Pivotal is the logical choice since it's already available and some of us have experience with it now.

It's still worthwhile to use Issues for tracking things at a high-level. I would like to try keeping milestones and larger tickets in here (because they have a bit more visibility to anyone watching the repository), with links in the issues to individual stories in Pivotal.

Dmose, can you make a Pivotal project for Gladius?

**Comment by dmose** [comment]
https://www.pivotaltracker.com/projects/373719 is it.
