### ISSUE TITLE
Test 5. "common/Math/Vector2: Constants (4, 0, 4)" Fails

### ISSUE THREAD

**Issue by GUSCRAWFORD** [gladiusjs/gladius-core#51]
I cloned an updated version, and after running the tests, realized that test 5 fails.

I do veleive JSilver mentioned he added the Math module to the test build.

Test 5. "common/Math/Vector2: Constants (4, 0, 4)" Fails

Here's the User Agent string from the test-output heading.
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.220 Safari/535.1

I'm using chrome 13.0.782.220

The test only fails in chrome!

The test heading appears like so in chrome:
common/Math/Vector2: Constants (4, 0, 4)

In firefox, the test doesn't fail and the paraemter list is ordered differently.
common/Math/Vector2: Constants (0, 4, 4)

**Comment by modeswitch** [comment]
Needs more details. Which browser/version?

**Comment by modeswitch** [comment]
Tracked against gladius.math instead.
