### ISSUE TITLE
Core and Math test suites don't run

### ISSUE THREAD

**Issue by jbuck** [gladiusjs/gladius-core#56]
[17:07:23.735] A call to document.write() from an asynchronously-loaded external script was ignored. @ http://localhost:8080/gladius/external/gladius.math/test/ (x2)
[17:11:12.730] A call to document.write() from an asynchronously-loaded external script was ignored. @ http://localhost:8080/gladius/test/

I get these errors, which prevents the test suites from running. I know there was a quick fix for this in IRC last night, but I can't remember what it was.

**Comment by dmose** [comment]
On 10/18/11 2:11 PM, Jon Buckley wrote:

> [17:07:23.735] A call to document.write() from an asynchronously-loaded external script was ignored. @ http://localhost:8080/gladius/external/gladius.math/test/ (x2)
> [17:11:12.730] A call to document.write() from an asynchronously-loaded external script was ignored. @ http://localhost:8080/gladius/test/
> 
> I get these errors, which prevents the test suites from running. I know there was a quick fix for this in IRC last night, but I can't remember what it was.
> 
> https://www.pivotaltracker.com/projects/373719?story_id=19809465

The actual fix involves renaming one of the files in the repo & 
buildsystem; from what I can see, that fix will have to be made on a 
non-OS X machine and then checked in before the OS X devs can see the 
benefits.

Dan

**Comment by modeswitch** [comment]
The quick fix is to rename Math.js to something else (and fix up its references). I'm preparing a larger change to break up Math.js into other files so it will also be easier to work with. The fix is for gladius.math, even though the bug affects both projects.

**Comment by jbuck** [comment]
Fixed when @dmose landed 1f62e194
