### ISSUE TITLE
Manual (reference and tutorial materials)

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#8]
Let's create a manual that covers the various parts of the engine and how to use it, along with example code for each section (where appropriate). We can also make an appendix of runnable example programs to go with the manual.

**Comment by dmose** [comment]
Yeah, this sounds like a fine idea.  I know the popcorn team has put together a great example video format that seems worth using for some sorts of stuff, at least.

**Comment by modeswitch** [comment]
I reorganized the wiki pages and started writing some documentation. More to come.
