### ISSUE TITLE
Renderer fails on two entities with model components

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#83]
See cube.js in this [commit](https://github.com/alankligman/gladius/commit/b7069c288efbe82887b77568ee4b204113d9237f). Renderer fails with

```
[12:46:32.801] compileMap.elements is undefined @ http://localhost/~afk/project/gladius.git/external/CubicVR.js/source/CubicVR.Mesh.js:1635
```

**Comment by secretrobotron** [comment]
Looks like Cubic doesn't protect against multiple calls to `compile()`. This is fixed upstream now. PR filed.

**Comment by modeswitch** [comment]
Fixed.
